#!/usr/bin/env perl

use common::sense;
use autodie;
use Getopt::Long;
use File::Path 'make_path';
use Pod::Usage;
use Readonly;

main();

# --------------------------------------------------
sub main {
    my %args = get_args();

    if ($args{'help'} || $args{'man_page'}) {
        pod2usage({
            -exitval => 0,
            -verbose => $args{'man_page'} ? 2 : 1
        });
    }; 

    unless ($args{'in_dir'}) {
        pod2usage('No input directory');
    }

    unless ($args{'out_dir'}) {
        pod2usage('No output directory');
    }

    unless (-d $args{'in_dir'}) {
        pod2usage("Bad input dir ($args{'in_dir'})");
    }

    unless (-d $args{'out_dir'}) {
        make_path($args{'out_dir'});    
    }

    say "OK";
}

# --------------------------------------------------
sub get_args {
    my %args;
    GetOptions(
        \%args,
        'in_dir=s',
        'out_dir=s',
        'help',
        'man',
    ) or pod2usage(2);

    return %args;
}

__END__

# --------------------------------------------------

=pod

=head1 NAME

run-fizkin - run fizkin

=head1 SYNOPSIS

  run-fizkin -i input-dir -o output-dir

Options:

  --input_dir   Input directory (FASTA)
  --output_dir  Output directory (FASTA)
  --help        Show brief help and exit
  --man         Show full documentation

=head1 DESCRIPTION

Describe what the script does, what input it expects, what output it
creates, etc.

=head1 SEE ALSO

perl.

=head1 AUTHOR

Ken Youens-Clark E<lt>kyclark@email.arizona.eduE<gt>.

=head1 COPYRIGHT

Copyright (c) 2015 kyclark

This module is free software; you can redistribute it and/or
modify it under the terms of the GPL (either version 1, or at
your option, any later version) or the Artistic License 2.0.
Refer to LICENSE for the full license text and to DISCLAIMER for
additional warranty disclaimers.

=cut
